const stories = [
    {n:1, cat:"culture", title:"Monpa Culture – Tawang", img:"https://upload.wikimedia.org/wikipedia/commons/2/21/Aji_Lamu_Folk_Dance_of_Arunachal_Pradesh.jpg", desc:" The Monpa community is closely associated with Tawang and has a rich Buddhist cultural heritage. Their traditional dress, food, architecture and festivals give travellers a deeper understanding of life in the Himalayan region . Why travel for it: Experience Monpa traditions alongside Tawang’s mountain and monastery landscape."},
    {n:2, cat:"culture", title:"Apatani Culture – Ziro Valley", img:"https://upload.wikimedia.org/wikipedia/commons/2/29/Apatani_tribal_women.jpg", desc:"The Apatani people are known for their distinctive traditions and the unique agricultural landscape of Ziro Valley. Their villages and traditional farming practices offer a different side of Arunachal. Why travel for it: Explore village life, traditional agriculture and the cultural landscape of Ziro."},
    {n:3, cat:"culture", title:"Adi Culture – Siang Region", img:"https://upload.wikimedia.org/wikipedia/commons/0/01/Portrait_of_Adi_Tribals_from_Arunachal_Pradesh.jpg", desc:"The Adi communities of the Siang region have rich traditions of music, dance, storytelling and community life. Their connection with the mountains and rivers adds a strong cultural element to the region. Why travel for it: Combine river and mountain landscapes with authentic local cultural experiences."},
    {n:4, cat:"culture", title:"Nyishi Culture – Papum Pare & Surrounding Areas", img:"https://upload.wikimedia.org/wikipedia/commons/f/f7/Nyokum_festival_Nyishi.JPG", desc:"The Nyishi are one of Arunachal Pradesh’s major Indigenous communities, with distinctive traditions, clothing, festivals and social practices. Their heritage helps travellers understand the cultural diversity beyond the state's famous destinations. Why travel for it: Discover a culture that is often missed on a conventional Arunachal itinerary."},
    {n:5, cat:"monuments", title:"Tawang Monastery", img:"https://upload.wikimedia.org/wikipedia/commons/b/be/Sakyamuni_Buddha.jpg", desc:"Tawang Monastery is one of the most important Buddhist monasteries in Arunachal Pradesh. Its mountain setting, murals, prayer halls and Buddhist heritage make it a major cultural landmark. Why travel for it: Combine Himalayan scenery with one of the region’s most important Buddhist sites."},
    {n:6, cat:"monuments", title:"Malinithan Temple", img:"https://upload.wikimedia.org/wikipedia/commons/b/b8/Malini_Than_temple_complex.jpg", desc:"Malinithan is an important archaeological and religious site near Likabali. Its stone sculptures and historical associations provide a glimpse into the region’s older cultural connections. Why travel for it: Discover an archaeological and spiritual site away from the usual mountain circuit."},
    {n:7, cat:"monuments", title:"Bhismaknagar Fort", img:"https://welcomearunachal.com/wp-content/uploads/2025/09/fort-image.jpg", desc:"Bhismaknagar is an ancient fortified archaeological site near Roing. Its stone structures and historical associations make it interesting for travellers curious about Arunachal’s early history. Why travel for it: Add archaeology and history to a trip through the Dibang Valley."},
    {n:8, cat:"monuments", title:"Golden Pagoda – Namsai", img:"https://talesofthehiddentrails.wordpress.com/wp-content/uploads/2020/08/116697587_1160035884369928_5938512881065619576_n-2.jpg", desc:"The Golden Pagoda at Namsai is a striking Buddhist temple complex surrounded by greenery. Its architecture and peaceful setting make it an appealing cultural stop in eastern Arunachal. Why travel for it: A visually impressive Buddhist experience combined with a calm natural setting."},
    {n:9, cat:"arts", title:"Idu Mishmi Shamanic Traditions", img:"https://upload.wikimedia.org/wikipedia/commons/5/59/A_photo_of_a_famous_Idu-Mishmi_shaman_lived_at_high_altitudes_along_Indo-china_border._Photo_courtesy_RIWATCH.jpg", desc:"The Idu Mishmi have a rich oral tradition involving chants, rituals, myths and stories passed down through generations. These traditions provide insight into the community’s worldview and relationship with nature.Why travel for it: Experience living oral traditions and stories connected to the forest landscape."},
    {n:10, cat:"arts", title:"Monpa Thangka Painting", img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSGh4IzHod2RF8lZ7wzOaBKo4NXvMQwT5VtstyKrP2NaA6dtembPx8rYYc&s=10", desc:"Thangka painting is an important Buddhist art tradition among the Monpa community. These detailed paintings often depict Buddhist themes and require considerable artistic skill.Why travel for it: See traditional artwork being created and understand its cultural meaning"},
    {n:11, cat:"arts", title:"Wancho Woodcarving", img:"https://media.assettype.com/deccanherald%2F2024-01%2F29a4cd18-4098-4915-9ce9-89ce4e395cb1%2Fcq5dam_web_1800_600.jpeg", desc:"Traditional woodcarving is an important part of Wancho cultural heritage in eastern Arunachal Pradesh. Carved objects and traditional designs reflect their craftsmanship and identity. Why travel for it: Discover distinctive local craftsmanship and artisan traditions"},
    {n:12,cat:"arts",title:"Adi Folk Songs & Storytelling", img:"https://www.etribaltribune.com/images/V1I11/m-_37.jpg", desc:"Traditional Adi songs and oral storytelling preserve stories, history and community knowledge. Music and performances offer a lively way to experience local heritage. Why travel for it: Turn cultural history into a live experience through music and storytelling."},
    {n:13,cat:"festivals",title:"Losar – Tawang", img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSM5sTgHFkvtIIMwnWBdf6wsKkGNGaye66kkd5P5-X5_ugJIGzEZ0vS7M0S&s=10", desc:"Losar is an important festival celebrated by the Monpa community to mark the Tibetan Buddhist New Year. Celebrations include prayers, traditional food, costumes and cultural activities. Why travel for it: Experience Tawang’s Buddhist culture during an important annual celebration."},
    {n:14,cat:"festivals",title:"Ziro Music Festival", img:"https://media-cdn.tripadvisor.com/media/attractions-splice-spp-720x480/11/83/2c/7f.jpg", desc:"The Ziro Music Festival brings musicians and audiences together in the scenic Ziro Valley. It combines live music with the valley’s local atmosphere, food and cultural surroundings.Why travel for it: A mix of music, outdoor experience and the unique atmosphere of Ziro Valley."},
    {n:15,cat:"festivals",title:"Solung Festival – Adi Community", img:"https://amazingarunachal.com/wp-content/uploads/2025/11/DSC1690_P-scaled.jpg", desc:"Solung is an important Adi festival connected with agriculture, prosperity and community life. Traditional songs, dances, rituals and food are part of the celebrations. Why travel for it: Experience Adi traditions through a vibrant community celebration."},
    {n:16,cat:"festivals",title:"Si-Donyi Festival – Tagin Community", img:"https://utsav.gov.in/public/uploads/event_picture_image/event_1983/1710950140936002329.jpg", desc:"Si-Donyi is an important festival of the Tagin community, celebrating cultural traditions and community well-being. Traditional rituals, songs and dances bring people together. Why travel for it: See Tagin traditions through a festival that brings the community together."},
    {n:17,cat:"crafts",title:"Monpa Handwoven Textiles", img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQk7P_TTtHYx1WlVIUvF5TNskKORerweil_irqNIbjSpUryLBwu_Cc_q1pk&s=10", desc:"Monpa communities have traditional weaving practices involving distinctive patterns, colours and clothing. Exploring the process gives travellers a closer look at Himalayan textile traditions. Why travel for it: See traditional weaving and discover locally made textiles."},
    {n:18,cat:"crafts",title:"Apatani Weaving", img:"https://img.perniaspopupshop.com/store-locator-v2/uploads/PWA_Main_Image_Apatani_6fd6e4aca0.jpg", desc:"Traditional Apatani textiles are known for distinctive designs connected with local culture. The craft offers insight into traditional clothing and weaving practices in Ziro. Why travel for it: Explore local weaving while visiting the cultural landscape of Ziro."},
    {n:19,cat:"crafts",title:"Cane & Bamboo Craft", img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTTMch5Pt4PqFqkGA-V7JJIwnY8x2EZaBFiP9JpIRtBv3YSnq0m_BISSPg&s=10", desc:"Cane and bamboo are widely used across Arunachal Pradesh to make baskets, furniture, household objects and other products. The craft reflects the practical use of locally available materials. Why travel for it: Watch everyday natural materials being transformed into useful handmade products."},
    {n:20,cat:"crafts",title:"Nyishi Traditional Crafts", img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSCc-7TuF_d-X1BWQhpzstnPETu1Cl0qjjTwRG95-WAcUkyKK_MzPyJwKOP&s=10", desc:"Nyishi artisans create traditional objects and accessories using locally available materials. These crafts are connected with community identity and traditional skills. Why travel for it: Discover handmade objects that carry cultural meaning rather than mass-produced souvenirs."},
    {n:21,cat:"food",title:"Thukpa", img:"https://foodtrails25.com/wp-content/uploads/2019/09/How-to-make-Thukpa-Noodle-Soup-500x500.jpg", desc:"Thukpa is a popular noodle soup in the Himalayan regions of Arunachal Pradesh, especially around Tawang. Noodles, vegetables and local flavours make it a comforting part of the region’s food culture. Why travel for it: Taste Himalayan comfort food while exploring Tawang."},
    {n:22,cat:"food",title:"Zan", img:"https://i.pinimg.com/736x/c5/70/3c/c5703cdc21b208b1520c57e5ec800a73.jpg", desc:"Zan is a traditional Monpa dish made using millet or other grains and associated with the Tawang region. It represents the simple and nourishing food traditions of Himalayan communities. Why travel for it: Try a traditional local dish that visitors may not encounter on a typical food tour"},
    {n:23,cat:"food",title:"Apong", img:"https://www.cuisineindiasociety.in/wp/wp-content/uploads/2025/10/RiceBeer.jpg", desc:"Apong is a traditional fermented rice-based drink associated with several communities in Arunachal Pradesh, particularly in the eastern regions. Its preparation and use are connected with community gatherings and cultural occasions. Why travel for it: Learn about traditional fermentation and the role of food and drink in community life."},
    {n:24,cat:"food",title:"Smoked Meat & Local Bamboo-Shoot Dishes", img:"https://rootsandleisure.com/wp-content/uploads/2020/07/Rootsandleisure_Naga-pork-with-bamboo-shoot.jpg", desc:"Smoked meat and bamboo-shoot preparations are found in several food traditions across Arunachal Pradesh. They reflect local ingredients and traditional methods of cooking and preservation. Why travel for it: Experience distinctive local flavours and traditional cooking methods."},
];

const labels={culture:"Regional Cultures",monuments:"Historic Monuments & Temples",arts:"Folklore, Art & Literature",festivals:"Festivals",crafts:"Handicrafts & Textiles",food:"Traditional Cuisine"};
const categoryImages={
  culture:"https://images.unsplash.com/photo-1539650116574-75c0c6d73f6e?auto=format&fit=crop&w=900&q=80",
  monuments:"https://images.unsplash.com/photo-1564507592333-c60657eea523?auto=format&fit=crop&w=900&q=80",
  arts:"https://images.unsplash.com/photo-1577083552431-6e5fd01988c5?auto=format&fit=crop&w=900&q=80",
  festivals:"https://images.unsplash.com/photo-1604608672516-f1b9c1b1a0a5?auto=format&fit=crop&w=900&q=80",
  crafts:"https://images.unsplash.com/photo-1610701596007-11502861dcfa?auto=format&fit=crop&w=900&q=80",
  food:"https://images.unsplash.com/photo-1585937421612-70a008356fbe?auto=format&fit=crop&w=900&q=80"
};
const collection=document.getElementById("collection"),search=document.getElementById("search"),filter=document.getElementById("categoryFilter");

function openStory(id){
  const s=stories.find(x=>x.n===id);
  document.getElementById("modalNumber").textContent=String(s.n).padStart(2,"0");
  document.getElementById("modalCategory").textContent=labels[s.cat];
  document.getElementById("modalTitle").textContent=s.title;
  document.getElementById("modalDescription").textContent=s.desc;
  document.getElementById("modal").classList.add("open");
  document.getElementById("modal").setAttribute("aria-hidden","false");
}
function render(){
  const q=search.value.toLowerCase().trim(), cat=filter.value;
  const result=stories.filter(s=>(cat==="all"||s.cat===cat)&&(!q||(s.title+" "+s.desc+" "+labels[s.cat]).toLowerCase().includes(q)));
  collection.innerHTML=result.length?result.map(s=>`
    <article class="story" data-id="${s.n}">
      <img class="story-image" src="${s.img}" alt="${s.title}" loading="lazy">
      <div><div class="story-number">${String(s.n).padStart(2,"0")}</div><div class="story-cat">${labels[s.cat]}</div></div>
      <div><h3>${s.title}</h3><p>${s.desc}</p></div><a class="story-arrow" target="_blank" rel="noopener" aria-label="Read source for ${s.title}">↗</a>
    </article>`).join(""):`<div class="empty">No stories found. Try another search.</div>`;
  document.querySelectorAll(".story").forEach(el=>el.addEventListener("click",()=>openStory(+el.dataset.id)));
}
function closeModal(){document.getElementById("modal").classList.remove("open");document.getElementById("modal").setAttribute("aria-hidden","true")}
search.addEventListener("input",render); filter.addEventListener("change",render);
document.querySelectorAll(".cat-card").forEach(btn=>btn.addEventListener("click",()=>{
  filter.value=btn.dataset.cat; document.getElementById("discover").scrollIntoView({behavior:"smooth"}); render();
}));
document.querySelectorAll("[data-close]").forEach(x=>x.addEventListener("click",closeModal));
document.addEventListener("keydown",e=>{if(e.key==="Escape")closeModal()});
render();