const stories = [
    {n:1, cat:"culture", title:"Gond Culture - Bastar", img:"https://i.pinimg.com/564x/c4/57/18/c45718d48d2c2ecfa3e3df932ab75dcf.jpg", desc:"The Gonds are the heart of Bastar, split into groups like Maria, Muria and Dorla, each with their own dialect and style. Their beliefs are built around nature and ancestry rather than anything you'd recognize as mainstream religion. Their biggest cultural moment is Bastar Dussehra, a 75-day festival that looks nothing like the version celebrated elsewhere in India.<br>Why travel for it: See and experience a Dussehra that feels like a totally different festival altogether."},
    {n:2, cat:"culture", title:"Abujhmariya Culture - Abujhmarh Hills", img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS4CEO1WI1qZH5DOLp0TORLLj2KggjbG0dAGOUirQbwhSGa8SyV0dsl_Yo&s=10", desc:"This tribe lives in one of India's last unmapped forest stretches, largely isolated even today. Their most fascinating tradition is the Ghotul, a youth dormitory where young people learn community life and customs; still active, not just history.<br>Why travel for it: a rare glimpse into a living social system, about as close as you can get to seeing an untouched, functioning way of life."},
    {n:3, cat:"culture", title:"Halba Culture -Bastar Region", img:"https://www.newsinc24.com/uploads/news/HalbaTribes.jpg", desc:"Unlike most tribes here, the Halba were once tied to Bastar's royal courts as soldiers, so they became settled farmers instead of forest dwellers. Their story shows how power and politics shaped tribal identity just as much as nature did.<br>Why travel for it: a different, more political side to Bastar's tribal history."},
    {n:4, cat:"culture", title:"Kamar Culture (Gariaband & Dhamtari)", img:"https://cf-images.assettype.com/nationalherald%2F2023-08%2F20f10b8e-8bdb-4ebc-8fb3-f4e70c355265%2F1015025960.?rect=0%2C0%2C3864%2C2029&w=1200&ar=40%3A21&auto=format%2Ccompress&ogImage=true&mode=crop&enlarge=true&overlay=false&overlay_position=bottom&overlay_width=100", desc:"The Kamar community still builds traditional mud homes with hand-plastered floors, much like their ancestors did. In 2023, they made history by becoming the first tribe in the state to legally secure rights to their own land.<br>Why travel for it: a living example of a tribal community's fight for land actually paying off."},
    {n:5, cat:"monuments", title:"The Chitrakote Falls", img:"https://portal-tourism.cgstate.gov.in//files/CHITRAKOTE%20Poster%20Image.jpg", desc:"The Chitrakote Falls is a natural waterfall on the Indravati River, located in the west of Jagdalpur, in Bastar district in the Indian state of Chhattisgarh.It is the widest waterfall in India, reaching a width of nearly 300 metres (980 ft) during the peak monsoon season.<br>Why travel for it: Because of its width and horseshoe shape during the monsoon season, it is often called the Niagara Falls of India"},
    {n:6, cat:"monuments", title:"Kotumsar cave", img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR9CNCWKLqN-z-B8uqiSLpZJYK47P59pN5MuN225FEUobXyQNdzqkJOHE2A&s=10", desc:"Kotumsar cave is a limestone cave located near Jagdalpur in the Indian state of Chhattisgarh. Kotumsar cave is a major attraction for people interested in ecotourism. Kotumsar cave formed on the Kanger limestone belt, near the bank of the River Kanger.<br>Why travel for it:The Kotumsar Cave in Central India is one of the most biologically explored caves in India."},
    {n:7, cat:"monuments", title:"Kotgarh Fort ", img:"https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhJbxk4fw50MWHid8n-g4Nep9iMYQHNQbXeREC9IlTJvLNpWkAL4zQsxfvaLR38wZY5DHIgqsUlCYJ8b7FI_VHyJJuq9ZKzVc53oRyHwSnP6ekeugDG6fzxNrISXBpQQ9jOUgKqyoEBucmA/s5152/kotgarh_fort_janjgir.JPG", desc:"Kotgarh Fort is a captivating historical site situated in Chhattisgarh, India, dating back to the 10th century and associated with the Kalachuri dynasty.<br>Why travel for it: This well-preserved fort features impressive mud walls and a serene pond, making it an ideal destination for those interested in India's rich archaeological heritage."},
    {n:8, cat:"monuments", title:"Shivani Maa Temple", img:"https://seawatersports.com/images/places/maa-shivani-temple.png", desc:"Located in the Kanker District, Chhattisgarh, Shivani Temple is a famous temple dedicated to a combination of two Goddesses, Durga Maa and Kali Maa. It is one of the oldest temples in the city. The structure of the temple shows the ancient style of building temples and reflects an ethnic and traditional look.<br>Why travel for it: Such architectural grandeur of an idol is only present in two places in the world- one here in Kanker, Chhattisgarh and the other is in Kolkata."},
    {n:9, cat:"arts", title:"Godna", img:"https://www.sahapedia.org/sites/default/files/styles/sp_page_banner_800x800/public/Godna%20banner.jpg?itok=uGRApPEx", desc:"Godna art is a tribal art that has its roots in the Gond tribe of Chhattisgarh. This Chhattisgarh tribal art is originally a form of body tattooing that involves the use of natural dyes and some traditional tools to make various patterns on the body.<br>Why travel for it: The Godna art designs are an embodiment of the cultural prevailments, personal preferences, social and historical nuances"},
    {n:10, cat:"arts", title:"Raut Nacha", img:"https://www.gosahin.com/go/p/i/1560193683_raut-nacha-dance.jpg", desc:"Raut dance is a traditional dance of the Yadav community which is performed on Deepawali. In this dance, the Rauts, wearing a special costume, sing and dance in group with stick in their hands in the pathways of the village. After the performance of dance in the house of every householder, they gives blessings to every household by singing songs of blessings. ‘Timki’, ‘Mohri’, ‘Dafda’, ‘Dholak’, ‘Singabaja’ etc. are the main instruments of this dance. ‘Dhohas’ are sung in between the dance.<br>Why travel for it:Experience the vibrant Raut Dance, where traditional costumes, folk music, and joyful group performances celebrate the rich culture of the Yadav community."},
    {n:11,cat:"arts",title:"Pandwani – Music form & Folk Ballad", img:"https://www.theartlifegallery.com/blog/wp-content/uploads/2023/07/Image-01-15.jpg", desc:"Pandwani means Pandavwani – that is Panda Katha, a story of Mahabharata. Pandwani is a folk ballad form performed predominantly in Chhattisgarh. It depicts the story of the Pandavas, the leading characters in the epic Mahabharata. It is narrated in a very lively form, almost constructing the scenes in the minds of the audience.<br>Why travel for it: The artists in the Pandwani narration consist of a lead artist and some supporting singers and musicians."},
    {n:12,cat:"arts",title:"Rock Paintings of Raigarh", img:"https://www.sahapedia.org/sites/default/files/styles/sp_inline_images/public/inline-images/5_6.jpg?itok=F9Jjuc7X", desc:"Raigarh is known for its ancient rock paintings and prehistoric sites.Places like Basnajhar and Kabra Pahar showcase fascinating rock art.The paintings depict early human life, animals, hunting, and dancing scenes.<br>Why travel for it:Discover ancient rock art and glimpse the lives of early humans."},
    {n:13,cat:"festivals",title:"Goncha festival", img:"https://culturetravel.in/images/cultureEvents/gonchaFestival/img_2.jpg", desc:"Goncha festival is celebrated every year during the 'Rath Yatra' in Jagdalpur. It is one of the most awaited tribal festivals celebrated with much fervor in the state. During this festival, mostly tribals participate in the celebration. They use a sort-of pistol made from bamboo and called, goncha and a fruit as the bullet called, tukki to shoot at each other for fun and amusement.<br>Why travel for it: Experience the vibrant traditions, colorful celebrations, and unique cultural heritage of the Goncha Festival."},
    {n:14,cat:"festivals",title:"Bhoramdeo Festival", img:"https://cdn.guidetour.in/wp-content/uploads/2023/05/Festival-of-Chhattisgarh.jpg", desc:"The Bhoramdeo Festival is an annual celebration held in the Bhoramdeo Temple complex, located in the Kawardha district of Chhattisgarh. The festival is dedicated to Lord Shiva and celebrates the rich cultural and religious heritage of the region.<br>Why travel for it:The Bhoramdeo Festival attracts devotees and tourists alike, offering a unique glimpse into the local customs and religious practices."},
    {n:15,cat:"festivals",title:"Chakradhar Samaroh", img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRmoE6xtS4oYUGoUWOw-h7XpElkiCctlsDICj5ONOX_Kg&s=10", desc:"Chakradhar Samaroh is the music festival of Chattisgarh. This cultural fest is hosted to commemorate the glorious memory of Maharaja Chakradhar Singh, who was a former ruler and a great tabla player and dancer.<br>Why travel for it:This festival is known for its special music and dance performances."},
    {n:16,cat:"festivals",title:"Hareli", img:"https://villagesquare.in/wp-content/uploads/2025/07/LEAD-31.jpg", desc:"Hareli is a traditional festival celebrated in the state of Chhattisgarh, particularly in the rural and tribal areas. Held annually around the end of July or early August, Hareli marks the beginning of the monsoon season and is a time for celebrating agriculture, fertility, and prosperity.<br>Why travel for it: The festival is known for its vibrant rituals, community gatherings, and traditional practices"},
    {n:17,cat:"crafts",title:" Terracotta Figurines", img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSm5IRioPZ6rPC_A5FFtOAuNNOjhgyLWYnP7lrufQ04vg&s=10", desc:"Terracotta craft is one of the hidden gems of Kumhar Para village in Chhattisgarh.<br>Why travel for it:The significance of terracotta lies in its uniqueness, intricate designs, sustainable practices, and the communities that sustain it."},
    {n:18,cat:"crafts",title:"Loha Shilp", img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT46kqUWig_whSO0mVU-uXDtYPDFKdpUNWZTvWnd8GQ_4RiIs_aw2690z4&s=10", desc:"The Bastar Iron Craft, also known as “Loha Shilp”, has a long and distinct history in Chhattisgarh's Bastar area. This elegantly simple art form developed with the region's iron working culture.<br>Why travel for it: Beautiful lamps(deepaks) embellished with birds, or animal images, are among the traditional works."},
    {n:19,cat:"crafts",title:"Dhokra Art", img:"https://www.shambhavicreations.co.in/cdn/shop/files/dhokra-handicraft-brass-cow-statue-multicolor-8-5-x-6-5-inch.jpg?v=1770192612", desc:"Dhokra is non–ferrous metal casting using the lost-wax casting technique. This sort of metal casting has been used in India for over 4,000 years and is still used. One of the earliest known lost wax artifacts is the dancing girl of Mohenjo-daro.<br>Why travel for it:At Kondagaon in Bastar district, artisans work on Dhokra sculptures which use an age-old wax-casting technique."},
    {n:20,cat:"crafts",title:"Kosa Silk", img:"https://weaverstory.com/cdn/shop/articles/Untitled_design_6_3cc0fb05-6d52-4428-ac87-15b2e6d513f6.jpg?v=1747373482", desc:"Hailing from the forests of Chhattisgarh, this special type of wild silk is celebrated for its earthy elegance and durable texture. Kosa silkworms are wild. They live on trees like Arjun and Sal in the vast forests of the region. This connection to nature is what makes Kosa silk a true wild silk.<br> Why travel for it: The entire craft is a beautiful example of humans working in harmony with their natural environment."},
    {n:21,cat:"food",title:"Angakar Roti", img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR2R6bbOGWhM-FZ4IpGSSdjY5sJZbbZ3LgXY2BBAcY-GJeBeYA_ORWNOvc&s=10", desc:"Angakar roti is a thick flatbread made from rice flour and mashed cooked rice, originating from the tribal regions of Chattisgarh. It is a breakfast dish made using the staple flour of the region."},
    {n:22,cat:"food",title:"Iddhar Kadhi", img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTvyoAvsaGrRt-oX0R5cN3e1VKfA4NzklbBdS7lhwL5zlvKuoHosK1E1VE&s=10", desc:"Iddhar Kadhi is a tangy traditional curry from Chattisgarh, made with ground urad dal and amaranth leaves. Iddhar is a dish that reflects the simplicity and earthiness of Chattisgarhi cuisine."},
    {n:23,cat:"food",title:"Muthia", img:"https://rakskitchen.net/wp-content/uploads/2022/12/muthiya-recipe-500x500.jpg", desc:"Muthia is made of boiled rice, rice flour, sesame seeds, garlic, coriander leaves,spices and salt. Muthia means fist and the dish got its name from the cooking method that requires the hand to be held in a fist to prepare it. It is mainly prepared during the winter season and is made either by frying or steaming. "},
    {n:24,cat:"food",title:"Khurmi", img:"https://i.pinimg.com/736x/bc/81/24/bc81247075192ef0c8050543fe59e2dd.jpg", desc:"is a fried sweet snack made of wheat flour, jaggery or sugar and ghee. To make the dish, wheat flour is kneaded with little ghee anda dough is prepared by adding jaggery or sugar mixed water. Small pieces of dough are rolled and fried in ghee on moderate flame. It can be easily stored for 2 to 3 weeks and is prepared mostly during the Deepawali festival"},
];

const labels={culture:"Regional Cultures",monuments:"Historic Monuments & Temples",arts:"Folklore, Art & Literature",festivals:"Festivals",crafts:"Handicrafts & Textiles",food:"Traditional Cuisine"};
const categoryImages={
  culture:"https://images.unsplash.com/photo-1539650116574-75c0c6d73f6e?auto=format&fit=crop&w=900&q=80",
  monuments:"https://images.unsplash.com/photo-1564507592333-c60657eea523?auto=format&fit=crop&w=900&q=80",
  arts:"https://images.unsplash.com/photo-1577083552431-6e5fd01988c5?auto=format&fit=crop&w=900&q=80",
  festivals:"https://images.unsplash.com/photo-1604608672516-f1b9c1b1a0a5?auto=format&fit=crop&w=900&q=80",
  crafts:"https://images.unsplash.com/photo-1610701596007-11502861dcfa?auto=format&fit=crop&w=900&q=80",
  food:"https://images.unsplash.com/photo-1585937421612-70a008356fbe?auto=format&fit=crop&w=900&q=80"
};
const collection=document.getElementById("collection"),search=document.getElementById("search"),filter=document.getElementById("categoryFilter");

function openStory(id){
  const s=stories.find(x=>x.n===id);
  document.getElementById("modalNumber").textContent=String(s.n).padStart(2,"0");
  document.getElementById("modalCategory").textContent=labels[s.cat];
  document.getElementById("modalTitle").textContent=s.title;
  document.getElementById("modalDescription").innerHTML=s.desc;
  document.getElementById("modal").classList.add("open");
  document.getElementById("modal").setAttribute("aria-hidden","false");
}
function render(){
  const q=search.value.toLowerCase().trim(), cat=filter.value;
  const result=stories.filter(s=>(cat==="all"||s.cat===cat)&&(!q||(s.title+" "+s.desc+" "+labels[s.cat]).toLowerCase().includes(q)));
  collection.innerHTML=result.length?result.map(s=>`
    <article class="story" data-id="${s.n}">
      <img class="story-image" src="${s.img}" alt="${s.title}" loading="lazy">
      <div><div class="story-number">${String(s.n).padStart(2,"0")}</div><div class="story-cat">${labels[s.cat]}</div></div>
      <div><h3>${s.title}</h3><p>${s.desc}</p></div><a class="story-arrow" target="_blank" rel="noopener" aria-label="Read source for ${s.title}">↗</a>
    </article>`).join(""):`<div class="empty">No stories found. Try another search.</div>`;
  document.querySelectorAll(".story").forEach(el=>el.addEventListener("click",()=>openStory(+el.dataset.id)));
}
function closeModal(){document.getElementById("modal").classList.remove("open");document.getElementById("modal").setAttribute("aria-hidden","true")}
search.addEventListener("input",render); filter.addEventListener("change",render);
document.querySelectorAll(".cat-card").forEach(btn=>btn.addEventListener("click",()=>{
  filter.value=btn.dataset.cat; document.getElementById("discover").scrollIntoView({behavior:"smooth"}); render();
}));
document.querySelectorAll("[data-close]").forEach(x=>x.addEventListener("click",closeModal));
document.addEventListener("keydown",e=>{if(e.key==="Escape")closeModal()});
render();